---
---

Check to make sure that you Terminal is using Git Bash by doing the following:
  
  - Select 'Tools' > 'Global Options' > 'Terminal'
  - New terminals open with: 'Git Bash'
  
The terminal should list the directory it is active in. If you open RStudio by opening `Project.Rproj` then you the terminal should have the directory that your ST563 group project repo is saved in. If not, then close RStudio and open the aforementioned file. 

*If you do not see that option, then you might not have Git Bash installed.*

From the terminal, you can use the following commands:

  - git add .
    - This will queue up the changes you've made
  
  - git commit -m "{comment}"
    - This will commit the changes you've made. Insert a description where {comment} is.
    
  - git push origin master
    - This will push your changes to the repository for everyone else to see!
    
  - git pull
    - This will pull the latest available version of the repo
    
  - git reset --hard
    - If you are having issues with file changes, or you are unable to pull the latest update/commit you're changes, then run this commande. *Should be a last resort*.

Any questions? Feel free to ask me, Joseph! 